CREATE TABLE Secret (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name varchar(200) NOT NULL
);

CREATE TABLE SuperSecret (
	  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	  name varchar(200) NOT NULL
);
